"use client";

import { useFamilyStore } from "@/store/family.store";
import {
	Card,
	CardHeader,
	CardTitle,
	CardContent,
} from "@/components/ui/card/card";
import { Button } from "@/components/ui/button/button";
import { Badge } from "@/components/ui/badge/badge";
import { motion } from "motion/react";

const flagTypeColors = {
	language: "text-red-400",
	bullying: "text-orange-400",
	"adult-content": "text-purple-400",
	spam: "text-yellow-400",
	other: "text-gray-400",
};

const flagTypeIcons = {
	language: "🤬",
	bullying: "😢",
	"adult-content": "🔞",
	spam: "📧",
	other: "⚠️",
};

export default function FamilyFlagsPage() {
	const getSelectedTeenAccount = useFamilyStore((s) => s.getSelectedTeenAccount);
	const dismissFlag = useFamilyStore((s) => s.dismissFlag);
	const addressFlag = useFamilyStore((s) => s.addressFlag);

	const teenAccount = getSelectedTeenAccount();

	if (!teenAccount) {
		return (
			<div className="flex items-center justify-center h-full">
				<p className="text-white/60">No teen account selected</p>
			</div>
		);
	}

	const { contentFlags } = teenAccount;
	const pending = contentFlags.filter((f) => f.status === "pending");
	const dismissed = contentFlags.filter((f) => f.status === "dismissed");
	const addressed = contentFlags.filter((f) => f.status === "addressed");

	return (
		<div className="h-full overflow-y-auto bg-[oklch(0.12_0.02_250)]">
			<div className="max-w-5xl mx-auto p-6 space-y-6">
				{/* Header */}
				<div>
					<h1 className="text-2xl font-bold text-white">Content Flags</h1>
					<p className="text-sm text-white/60 mt-1">
						AI-detected potentially concerning content from{" "}
						{teenAccount.user.displayName}
					</p>
				</div>

				{/* Warning Banner */}
				<motion.div
					className="px-4 py-3 bg-purple-500/20 border border-purple-500/30 rounded-lg"
					initial={{ opacity: 0, y: -10 }}
					animate={{ opacity: 1, y: 0 }}
				>
					<p className="text-sm text-purple-200 flex items-center gap-2">
						<span>🤖</span>
						<span>
							These flags are generated by AI and may have false positives.
							Review carefully before taking action.
						</span>
					</p>
				</motion.div>

				{/* Pending Flags */}
				<Card tilt={false}>
					<CardHeader>
						<div className="flex items-center justify-between">
							<CardTitle>Pending Review</CardTitle>
							{pending.length > 0 && (
								<Badge variant="danger">{pending.length} pending</Badge>
							)}
						</div>
					</CardHeader>
					<CardContent>
						{pending.length > 0 ? (
							<div className="space-y-4">
								{pending.map((flag) => (
									<motion.div
										key={flag.id}
										className="p-4 bg-white/5 border border-white/10 rounded-lg"
										initial={{ opacity: 0, y: 10 }}
										animate={{ opacity: 1, y: 0 }}
										whileHover={{ scale: 1.01 }}
									>
										<div className="space-y-4">
											{/* Flag Header */}
											<div className="flex items-start justify-between gap-4">
												<div className="flex items-start gap-3">
													<div className="text-3xl">
														{flagTypeIcons[flag.type]}
													</div>
													<div>
														<div className="flex items-center gap-2">
															<Badge variant="danger" className="text-xs">
																{flag.type.replace("-", " ").toUpperCase()}
															</Badge>
															<Badge variant="secondary" className="text-xs">
																{Math.round(flag.confidence * 100)}% confidence
															</Badge>
														</div>
														<p className="text-xs text-white/50 mt-1">
															Flagged on{" "}
															{new Date(flag.createdAt).toLocaleString()}
														</p>
													</div>
												</div>

												{/* Confidence Bar */}
												<div className="w-24">
													<div className="h-2 bg-white/10 rounded-full overflow-hidden">
														<motion.div
															className={`h-full ${
																flag.confidence > 0.8
																	? "bg-red-500"
																	: flag.confidence > 0.6
																		? "bg-orange-500"
																		: "bg-yellow-500"
															}`}
															initial={{ width: 0 }}
															animate={{ width: `${flag.confidence * 100}%` }}
															transition={{ duration: 0.5 }}
														/>
													</div>
												</div>
											</div>

											{/* Message Content */}
											<div className="p-3 bg-white/5 rounded-lg border border-white/10">
												<div className="text-xs text-white/50 mb-2">
													#{flag.message.channelName} in {flag.message.serverName}
												</div>
												<p className="text-white">{flag.message.content}</p>
												<div className="text-xs text-white/40 mt-2">
													{new Date(flag.message.timestamp).toLocaleString()}
												</div>
											</div>

											{/* Actions */}
											<div className="flex gap-2">
												<Button
													variant="primary"
													size="sm"
													onClick={() => addressFlag(teenAccount.id, flag.id)}
												>
													✓ Address with Teen
												</Button>
												<Button
													variant="secondary"
													size="sm"
													onClick={() => dismissFlag(teenAccount.id, flag.id)}
												>
													Dismiss as False Positive
												</Button>
											</div>
										</div>
									</motion.div>
								))}
							</div>
						) : (
							<div className="text-center py-8 text-white/60">
								<div className="text-4xl mb-2">✓</div>
								<p>No pending content flags</p>
							</div>
						)}
					</CardContent>
				</Card>

				{/* Addressed Flags */}
				{addressed.length > 0 && (
					<Card tilt={false}>
						<CardHeader>
							<CardTitle>Addressed</CardTitle>
						</CardHeader>
						<CardContent>
							<div className="space-y-3">
								{addressed.map((flag) => (
									<div
										key={flag.id}
										className="p-3 bg-green-500/10 border border-green-500/20 rounded-lg"
									>
										<div className="flex items-start gap-3">
											<div className="text-2xl">{flagTypeIcons[flag.type]}</div>
											<div className="flex-1">
												<div className="flex items-center gap-2">
													<Badge variant="secondary" className="text-xs">
														{flag.type.replace("-", " ")}
													</Badge>
													<Badge variant="primary" className="text-xs">
														Addressed
													</Badge>
												</div>
												<p className="text-sm text-white/70 mt-1 line-clamp-2">
													{flag.message.content}
												</p>
											</div>
										</div>
									</div>
								))}
							</div>
						</CardContent>
					</Card>
				)}

				{/* Dismissed Flags */}
				{dismissed.length > 0 && (
					<Card tilt={false}>
						<CardHeader>
							<CardTitle>Dismissed (False Positives)</CardTitle>
						</CardHeader>
						<CardContent>
							<div className="space-y-3">
								{dismissed.map((flag) => (
									<div
										key={flag.id}
										className="p-3 bg-white/5 border border-white/10 rounded-lg opacity-60"
									>
										<div className="flex items-start gap-3">
											<div className="text-2xl">{flagTypeIcons[flag.type]}</div>
											<div className="flex-1">
												<div className="flex items-center gap-2">
													<Badge variant="secondary" className="text-xs">
														{flag.type.replace("-", " ")}
													</Badge>
													<Badge className="text-xs bg-white/20">
														Dismissed
													</Badge>
												</div>
												<p className="text-sm text-white/50 mt-1 line-clamp-2">
													{flag.message.content}
												</p>
											</div>
										</div>
									</div>
								))}
							</div>
						</CardContent>
					</Card>
				)}

				{/* Info */}
				<div className="text-center text-sm text-white/40 space-y-1">
					<p>🤖 AI flags are meant to help, not replace conversation</p>
					<p>Talk to your teen about concerning content in a supportive way</p>
				</div>
			</div>
		</div>
	);
}
